"""Export the MLflow run history to committed, dependency-free files.

The tracking store itself is a SQLite database that is gitignored, so on its own
the experiment history only exists on the machine that ran the training. This
script reads that store and writes a CSV, a markdown table and a JSON summary
into ``mlops/mlflow/exports/``, which are committed.

That matters for three readers:

* anyone browsing the repository sees the recorded runs without installing
  MLflow or running anything;
* the deployed Streamlit app renders the comparison table straight from the CSV,
  so the Space shows the experiment history while never importing MLflow;
* the report can quote the table directly.

Called automatically at the end of ``python -m mlops.model_building.train``, and
runnable on its own:

    python -m scripts.export_mlflow_runs
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mlops.model_building import config  # noqa: E402
from mlops.model_building.utils import get_logger  # noqa: E402

logger = get_logger(__name__)

# Columns worth putting in front of a human, in the order they should read.
_MODEL_COLUMNS: list[tuple[str, str]] = [
    ("run_name", "Model"),
    ("metrics.cv_pr_auc_baseline", "CV PR-AUC (baseline)"),
    ("metrics.cv_pr_auc_tuned", "CV PR-AUC (tuned)"),
    ("metrics.test_pr_auc", "Test PR-AUC"),
    ("metrics.test_roc_auc", "Test ROC-AUC"),
    ("metrics.test_f1", "Test F1"),
    ("metrics.test_recall", "Test recall"),
    ("metrics.test_latency_median_ms", "Latency (ms)"),
]


def _load_runs() -> pd.DataFrame:
    """Read every run from the tracking store.

    Returns:
        A DataFrame of runs, or an empty one if MLflow or the store is absent.
    """
    try:
        import mlflow
    except ImportError:
        logger.warning("MLflow is not installed; nothing to export.")
        return pd.DataFrame()

    if not config.MLFLOW_DB_FILE.exists():
        logger.warning(
            "No tracking store at %s. Run training first.", config.MLFLOW_DB_FILE
        )
        return pd.DataFrame()

    mlflow.set_tracking_uri(config.MLFLOW_TRACKING_URI)
    experiment = mlflow.get_experiment_by_name(config.MLFLOW_EXPERIMENT_NAME)
    if experiment is None:
        logger.warning("Experiment %r not found.", config.MLFLOW_EXPERIMENT_NAME)
        return pd.DataFrame()

    runs = mlflow.search_runs([experiment.experiment_id])
    if runs.empty:
        return runs

    runs = runs.rename(columns={"tags.mlflow.runName": "run_name"})
    # A run with no parent is the session; the rest are its per-model children.
    parent_col = "tags.mlflow.parentRunId"
    runs["is_model_run"] = runs[parent_col].notna() if parent_col in runs else False
    return runs


def _markdown_table(models: pd.DataFrame) -> str:
    """Render the per-model comparison as a markdown table.

    Args:
        models: Child runs only, one row per candidate model.

    Returns:
        A markdown document, with the winning row marked.
    """
    present = [(key, label) for key, label in _MODEL_COLUMNS if key in models.columns]
    header = "| " + " | ".join(label for _, label in present) + " |"
    divider = "|" + "|".join(["---"] * len(present)) + "|"

    best = None
    if "metrics.test_pr_auc" in models.columns and not models.empty:
        best = models["metrics.test_pr_auc"].idxmax()

    lines = [header, divider]
    for index, row in models.iterrows():
        cells = []
        for key, _ in present:
            value = row.get(key)
            if isinstance(value, float):
                cells.append(f"{value:.2f}" if "latency" in key else f"{value:.4f}")
            else:
                cells.append(str(value))
        if index == best:
            cells[0] = f"**{cells[0]}**  <-- selected"
        lines.append("| " + " | ".join(cells) + " |")

    return "\n".join(lines)


def main() -> dict[str, Any]:
    """Write the export files and return a short summary."""
    runs = _load_runs()
    if runs.empty:
        logger.warning("No runs to export.")
        return {"runs": 0}

    config.MLFLOW_EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    # Full history: every run, every param and metric, for the record.
    keep = ["run_name", "status", "start_time", "is_model_run"] + sorted(
        c for c in runs.columns if c.startswith(("metrics.", "params."))
    )
    runs[[c for c in keep if c in runs.columns]].to_csv(
        config.MLFLOW_RUNS_CSV, index=False
    )

    models = runs[runs["is_model_run"]].copy()
    sessions = runs[~runs["is_model_run"]].copy()

    document = [
        "# MLflow run history",
        "",
        "Generated by `python -m scripts.export_mlflow_runs`; do not edit by hand.",
        "",
        f"Experiment: `{config.MLFLOW_EXPERIMENT_NAME}` "
        f"({len(sessions)} session run(s), {len(models)} model run(s))",
        "",
        "## Candidate models",
        "",
        _markdown_table(models.sort_values("metrics.test_pr_auc", ascending=False))
        if "metrics.test_pr_auc" in models.columns
        else "_No model runs recorded._",
        "",
        "Selection metric is PR-AUC: with a ~15.6% positive rate its baseline moves",
        "with class prevalence, so unlike accuracy it cannot be flattered by the",
        "84% of sessions that do not convert.",
        "",
    ]

    if not sessions.empty:
        session = sessions.sort_values("start_time").iloc[-1]
        document += [
            "## Latest training session",
            "",
            f"- Run: `{session['run_name']}`",
            f"- Selected model: **{session.get('tags.selected_model', 'n/a')}**",
        ]
        for key, label in [
            ("metrics.final_pr_auc", "PR-AUC at the operating threshold"),
            ("metrics.final_recall", "Recall"),
            ("metrics.operating_threshold", "Operating threshold"),
            ("metrics.model_size_mb", "Model size (MB)"),
        ]:
            if key in session and pd.notna(session[key]):
                document.append(f"- {label}: {session[key]}")
        document.append("")

    config.MLFLOW_RUNS_MARKDOWN.write_text("\n".join(document), encoding="utf-8")

    summary: dict[str, Any] = {
        "experiment": config.MLFLOW_EXPERIMENT_NAME,
        "n_session_runs": int(len(sessions)),
        "n_model_runs": int(len(models)),
        "models": {},
    }
    for _, row in models.iterrows():
        summary["models"][row["run_name"]] = {
            label: (None if pd.isna(row.get(key)) else float(row[key]))
            for key, label in _MODEL_COLUMNS[1:]
            if key in models.columns
        }
    if not sessions.empty:
        latest = sessions.sort_values("start_time").iloc[-1]
        summary["selected_model"] = latest.get("tags.selected_model")
    config.MLFLOW_SESSION_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    logger.info(
        "Exported %d run(s) -> %s",
        len(runs),
        config.MLFLOW_EXPORT_DIR.relative_to(config.PROJECT_ROOT),
    )
    return summary


if __name__ == "__main__":
    result = main()
    print(json.dumps(result, indent=2))
